on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID con el artifact de Terraform Plan' 
        required: true 
        type: string        
permissions:
  id-token: write # Necesario para OIDC
  contents: read  # Permite leer el código del repositorio
  actions: read
env:
  TF_WORKING_DIR: tf_work_folder/
jobs:
  terraform_apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM-APPLY

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.5

      - name: Download build artifact from triggered workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.inputs.run_id }}
          workflow_conclusion: success
          name: tfplan-artifact
          path: ${{ env.TF_WORKING_DIR }}/plan/

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_NAME }}" -backend-config="key=${{ vars.TF_STATE_FILE }}" -backend-config="region=${{ vars.AWS_REGION }}"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve ./plan/tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
