on:
  push:
    branches: [ "main" ]
    paths:
      - 'app_code/**'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

env:
  SOURCE_CODE_PATH: app_code/lambda_functions/
  S3_DESTINATION: s3://${{ secrets.CODE_S3_BUCKET}}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE  }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: zip files
        uses: vimtor/action-zip@v1.2
        with:
          files: ${{env.SOURCE_CODE_PATH}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-S3-Sync
          
      - name: Verify AWS Caller Identity
        run: aws sts get-caller-identity

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: execute py script 
        run: |
          python zip_files.py
        
      - name: Sync files to S3
        run: |
          echo "Sincronizando desde ${{env.SOURCE_CODE_PATH}} a ${{env.S3_DESTINATION}}"
          aws s3 sync "${{env.SOURCE_CODE_PATH}}" "${{env.S3_DESTINATION}}" --delete
